/**
 * The Pixel City plates, in stacking order, bottom first.
 *
 * Each import is a PNG that @rollup/plugin-url inlines as a base64 data URL
 * (rollup.config.mjs, `limit: Infinity`) — the route the three audio cues
 * already take, and the ONLY one that reaches users. Obsidian installs exactly
 * three files, manifest.json / main.js / styles.css, and manifest.json has no
 * field to declare more; a loose image beside them works on the dev machine
 * and is silently missing for everyone who installs from the catalog. That
 * failure cannot be found by testing locally, which is why it is written down
 * here rather than left to be rediscovered.
 *
 * The files are generated by art/pixel-city/skyline.py. The class names are what
 * the Pixel City block in styles.css animates on --gp-progress; the view
 * builds one <img> per entry, in this order, and nothing else about the theme
 * lives in TypeScript. tests/pixelCityArt.test.ts keeps the list, the files on
 * disk and the stylesheet in step, and holds the set inside its size budget.
 */
import sky1 from "./art/pixel-city/plates/sky-1.png";
import sky2 from "./art/pixel-city/plates/sky-2.png";
import sky3 from "./art/pixel-city/plates/sky-3.png";
import sky4 from "./art/pixel-city/plates/sky-4.png";
import sky5 from "./art/pixel-city/plates/sky-5.png";
import sky6 from "./art/pixel-city/plates/sky-6.png";
import sky7 from "./art/pixel-city/plates/sky-7.png";
import sky8 from "./art/pixel-city/plates/sky-8.png";
import stars from "./art/pixel-city/plates/stars.png";
import buildings from "./art/pixel-city/plates/buildings.png";
import windows1 from "./art/pixel-city/plates/windows-1.png";
import windows2 from "./art/pixel-city/plates/windows-2.png";
import windows3 from "./art/pixel-city/plates/windows-3.png";
import windows4 from "./art/pixel-city/plates/windows-4.png";
import windows5 from "./art/pixel-city/plates/windows-5.png";
import windows6 from "./art/pixel-city/plates/windows-6.png";

export interface PixelCityLayer {
  /** The class the theme's CSS addresses. Its suffix is the plate's file name. */
  readonly cls: string;
  /** A data URL once bundled; a plain path under vitest, which never renders it. */
  readonly src: string;
}

/**
 * Bottom to top: the eight sky plates (1 is the base; 2–8 each cross-fade in
 * over one seventh of the session, on top of the one before), the stars (fade
 * in over the last third), the buildings (static — the only layer that never
 * changes, so it can never ghost), then the six window waves (each eases on
 * over about 1% of the session, at thresholds spaced evenly from 40% to 80%).
 */
export const PIXEL_CITY_LAYERS: readonly PixelCityLayer[] = [
  { cls: "gp-pixel-city-sky-1", src: sky1 },
  { cls: "gp-pixel-city-sky-2", src: sky2 },
  { cls: "gp-pixel-city-sky-3", src: sky3 },
  { cls: "gp-pixel-city-sky-4", src: sky4 },
  { cls: "gp-pixel-city-sky-5", src: sky5 },
  { cls: "gp-pixel-city-sky-6", src: sky6 },
  { cls: "gp-pixel-city-sky-7", src: sky7 },
  { cls: "gp-pixel-city-sky-8", src: sky8 },
  { cls: "gp-pixel-city-stars", src: stars },
  { cls: "gp-pixel-city-buildings", src: buildings },
  { cls: "gp-pixel-city-windows-1", src: windows1 },
  { cls: "gp-pixel-city-windows-2", src: windows2 },
  { cls: "gp-pixel-city-windows-3", src: windows3 },
  { cls: "gp-pixel-city-windows-4", src: windows4 },
  { cls: "gp-pixel-city-windows-5", src: windows5 },
  { cls: "gp-pixel-city-windows-6", src: windows6 },
];
