/**
 * The Rooftop Skyline plates, in stacking order, bottom first.
 *
 * Each import is a PNG that @rollup/plugin-url inlines as a base64 data URL
 * (rollup.config.mjs, `limit: Infinity`) — the route the three audio cues
 * already take, and the ONLY one that reaches users. Obsidian installs exactly
 * three files, manifest.json / main.js / styles.css, and manifest.json has no
 * field to declare more; a loose image beside them works on the dev machine
 * and is silently missing for everyone who installs from the catalog. That
 * failure cannot be found by testing locally, which is why it is written down
 * here rather than left to be rediscovered.
 *
 * The files are generated by art/rooftop/skyline.py. The class names are what
 * the Rooftop Skyline block in styles.css animates on --gp-progress; the view
 * builds one <img> per entry, in this order, and nothing else about the theme
 * lives in TypeScript. tests/rooftopArt.test.ts keeps the list, the files on
 * disk and the stylesheet in step, and holds the set inside its size budget.
 */
import sky1 from "./art/rooftop/plates/sky-1.png";
import sky2 from "./art/rooftop/plates/sky-2.png";
import sky3 from "./art/rooftop/plates/sky-3.png";
import sky4 from "./art/rooftop/plates/sky-4.png";
import sky5 from "./art/rooftop/plates/sky-5.png";
import stars from "./art/rooftop/plates/stars.png";
import buildings from "./art/rooftop/plates/buildings.png";
import windows1 from "./art/rooftop/plates/windows-1.png";
import windows2 from "./art/rooftop/plates/windows-2.png";
import windows3 from "./art/rooftop/plates/windows-3.png";

export interface RooftopLayer {
  /** The class the theme's CSS addresses. Its suffix is the plate's file name. */
  readonly cls: string;
  /** A data URL once bundled; a plain path under vitest, which never renders it. */
  readonly src: string;
}

/**
 * Bottom to top: the five sky plates (1 is the base, 2–5 cross-fade in over
 * successive quarters of the session), the stars (fade in over the last
 * third), the buildings (static — the only layer that never changes, so it
 * can never ghost), then the three window waves (switch on at 40 / 60 / 80 %).
 */
export const ROOFTOP_LAYERS: readonly RooftopLayer[] = [
  { cls: "gp-rooftop-sky-1", src: sky1 },
  { cls: "gp-rooftop-sky-2", src: sky2 },
  { cls: "gp-rooftop-sky-3", src: sky3 },
  { cls: "gp-rooftop-sky-4", src: sky4 },
  { cls: "gp-rooftop-sky-5", src: sky5 },
  { cls: "gp-rooftop-stars", src: stars },
  { cls: "gp-rooftop-buildings", src: buildings },
  { cls: "gp-rooftop-windows-1", src: windows1 },
  { cls: "gp-rooftop-windows-2", src: windows2 },
  { cls: "gp-rooftop-windows-3", src: windows3 },
];
